"use client";

import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import BeachMap from "./BeachMap";

type Lang = "ko" | "en" | "zh" | "ja" | "fr";
type InfoKind = "sand" | "wave" | "jelly" | "shade" | "timer" | "aid" | "plan";
type Risk = "safe" | "caution" | "danger";

type Beach = { id:string; ko:string; en:string; district:string; coordinate:[number,number]; sand:number; wave:number; jelly:Risk; jellyArea:string; shade:{name:string; detail:string; walk:number}[] };
const beaches:Beach[] = [
  {id:"haeundae",ko:"해운대",en:"Haeundae",district:"해운대구",coordinate:[35.1587,129.1604],sand:42,wave:.8,jelly:"caution",jellyArea:"미포 방파제 인근",shade:[{name:"해운대 광장 그늘막",detail:"5번 망루 뒤편",walk:2},{name:"동백섬 산책로",detail:"수목 그늘 구간",walk:7}]},
  {id:"gwangalli",ko:"광안리",en:"Gwangalli",district:"수영구",coordinate:[35.1531,129.1186],sand:39,wave:.5,jelly:"safe",jellyArea:"관측 없음",shade:[{name:"만남의 광장",detail:"중앙 음수대 옆",walk:3},{name:"민락수변공원",detail:"해변 북쪽 수목",walk:8}]},
  {id:"songjeong",ko:"송정",en:"Songjeong",district:"해운대구",coordinate:[35.1798,129.1997],sand:44,wave:1.4,jelly:"caution",jellyArea:"죽도공원 앞 수역",shade:[{name:"죽도공원 입구",detail:"송일정 아래",walk:5},{name:"중앙 안내소",detail:"3번 망루 맞은편",walk:2}]},
  {id:"songdo",ko:"송도",en:"Songdo",district:"서구",coordinate:[35.0765,129.0172],sand:38,wave:.4,jelly:"safe",jellyArea:"관측 없음",shade:[{name:"송림공원",detail:"케이블카 하부",walk:4},{name:"분수광장 차양",detail:"중앙 안내소 옆",walk:2}]},
  {id:"dadaepo",ko:"다대포",en:"Dadaepo",district:"사하구",coordinate:[35.0483,128.9652],sand:41,wave:.7,jelly:"danger",jellyArea:"몰운대·낙동강 하구",shade:[{name:"해변공원 소나무숲",detail:"낙조분수 서편",walk:5},{name:"생태탐방로 쉼터",detail:"고우니길 2번 데크",walk:9}]},
  {id:"ilgwang",ko:"일광",en:"Ilgwang",district:"기장군",coordinate:[35.2633,129.2338],sand:43,wave:1,jelly:"caution",jellyArea:"학리항 인근",shade:[{name:"이천쉼터",detail:"해변 남쪽 산책로",walk:8},{name:"중앙 안내소 차양",detail:"해변 진입광장",walk:2}]},
  {id:"imrang",ko:"임랑",en:"Imrang",district:"기장군",coordinate:[35.3197,129.2659],sand:37,wave:.6,jelly:"safe",jellyArea:"관측 없음",shade:[{name:"임랑행정봉사실",detail:"해변 중앙 쉼터",walk:3},{name:"임랑공원 수목",detail:"주차장 맞은편",walk:6}]},
];
const languageNames:{id:Lang; native:string; english:string}[]=[{id:"ko",native:"한국어",english:"Korean"},{id:"en",native:"English",english:"English"},{id:"zh",native:"中文",english:"Chinese"},{id:"ja",native:"日本語",english:"Japanese"},{id:"fr",native:"Français",english:"French"}];
const labels:Record<Lang,Record<string,string>>={
  ko:{choose:"언어를 선택해 주세요",sub:"부산 바다를 더 안전하고 시원하게 즐겨요",start:"지도 열기",guide:"부산 해수욕장 안전 지도",change:"언어",tap:"지도 위 아이콘을 눌러 자세한 정보를 확인하세요",sand:"모래 온도",wave:"파도 높이",jelly:"해파리",shade:"그늘",timer:"햇빛 타이머",aid:"응급처치",plan:"다른 활동",safe:"안전",caution:"주의",danger:"위험",walk:"도보",min:"분",startTimer:"위치 확인 후 시작",pause:"잠시 멈춤",resume:"다시 시작",reset:"초기화",notify:"알림 허용",exposure:"노출 시간",next:"다음 알림"},
  en:{choose:"Choose your language",sub:"Enjoy Busan's beaches safely and comfortably",start:"Open map",guide:"Busan beach safety map",change:"Language",tap:"Tap an icon on the map for details",sand:"Sand temperature",wave:"Wave height",jelly:"Jellyfish",shade:"Shade",timer:"Sun timer",aid:"First aid",plan:"Other plans",safe:"Safe",caution:"Caution",danger:"Danger",walk:"Walk",min:"min",startTimer:"Locate & start",pause:"Pause",resume:"Resume",reset:"Reset",notify:"Allow alerts",exposure:"Exposure",next:"Next alert"},
  zh:{choose:"请选择语言",sub:"更安全、更舒适地享受釜山海滩",start:"打开地图",guide:"釜山海滩安全地图",change:"语言",tap:"点击地图图标查看详细信息",sand:"沙温",wave:"浪高",jelly:"水母",shade:"阴凉",timer:"日晒计时",aid:"急救",plan:"其他活动",safe:"安全",caution:"注意",danger:"危险",walk:"步行",min:"分钟",startTimer:"定位并开始",pause:"暂停",resume:"继续",reset:"重置",notify:"允许通知",exposure:"暴露时间",next:"下次提醒"},
  ja:{choose:"言語を選択してください",sub:"釜山の海を安全で快適に楽しもう",start:"地図を開く",guide:"釜山ビーチ安全マップ",change:"言語",tap:"地図上のアイコンを押して詳細を確認",sand:"砂の温度",wave:"波の高さ",jelly:"クラゲ",shade:"日陰",timer:"日光タイマー",aid:"応急処置",plan:"別の活動",safe:"安全",caution:"注意",danger:"危険",walk:"徒歩",min:"分",startTimer:"位置確認して開始",pause:"一時停止",resume:"再開",reset:"リセット",notify:"通知を許可",exposure:"経過時間",next:"次の通知"},
  fr:{choose:"Choisissez votre langue",sub:"Profitez des plages de Busan en toute sécurité",start:"Ouvrir la carte",guide:"Carte sécurité des plages de Busan",change:"Langue",tap:"Touchez une icône sur la carte pour les détails",sand:"Température du sable",wave:"Hauteur des vagues",jelly:"Méduses",shade:"Ombre",timer:"Minuteur solaire",aid:"Premiers soins",plan:"Autres activités",safe:"Sûr",caution:"Prudence",danger:"Danger",walk:"À pied",min:"min",startTimer:"Localiser et démarrer",pause:"Pause",resume:"Reprendre",reset:"Réinitialiser",notify:"Activer alertes",exposure:"Exposition",next:"Prochaine alerte"},
};
const riskOf=(b:Beach):Risk=>b.jelly==="danger"||b.wave>=1.3?"danger":b.sand>=42||b.wave>=.8||b.jelly==="caution"?"caution":"safe";
const fmt=(s:number)=>`${Math.floor(s/60).toString().padStart(2,"0")}:${(s%60).toString().padStart(2,"0")}`;

export default function Home(){
 const [lang,setLang]=useState<Lang>("ko"),[entered,setEntered]=useState(false),[beachId,setBeachId]=useState("haeundae"),[info,setInfo]=useState<InfoKind>("sand"),[seconds,setSeconds]=useState(0),[running,setRunning]=useState(false),[location,setLocation]=useState("");
 const notified=useRef(false),t=labels[lang],beach=beaches.find(b=>b.id===beachId)??beaches[0];
 useEffect(()=>{if(!running)return;const i=window.setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(i)},[running]);
 useEffect(()=>{if(seconds>=1200&&!notified.current){notified.current=true;if("Notification" in window&&Notification.permission==="granted")new Notification("뜨바다바",{body:"20분 동안 햇빛에 노출되었어요. 그늘에서 쉬어 주세요."})}},[seconds]);
 const begin=()=>{setLocation("위치 확인 중…");if(!navigator.geolocation){setLocation("타이머 시작됨");setRunning(true);return}navigator.geolocation.getCurrentPosition(()=>{setLocation(`${beach.ko} 인근 · 위치 확인됨`);setRunning(true)},()=>{setLocation("위치 권한 없이 타이머 시작됨");setRunning(true)},{timeout:6000})};
 if(!entered)return <Welcome lang={lang} setLang={setLang} onStart={()=>setEntered(true)}/>;
 return <main className="map-app"><header className="map-header"><button className="brand" onClick={()=>setInfo("sand")}><span className="logo-mini">뜨</span><span>뜨바다바<small>뜨거운 바다, 딴 바다로</small></span></button><p><i/> {t.guide}</p><button className="language-button" onClick={()=>setEntered(false)}>文 {t.change}</button></header>
  <section className="map-toolbar"><div className="beach-tabs">{beaches.map(b=><button key={b.id} className={b.id===beachId?"active":""} onClick={()=>setBeachId(b.id)}><i className={riskOf(b)}/>{lang==="ko"?b.ko:b.en}</button>)}</div><small>● 오늘 14:10 · 시연용 데이터</small></section>
  <section className="map-stage"><div className="map-title"><p>BUSAN BEACH MAP</p><h1>{lang==="ko"?beach.ko:beach.en} <span>Beach</span></h1><small>{t.tap}</small></div><BeachMap beach={beach} beaches={beaches} labels={t} activeInfo={info} onBeachSelect={setBeachId} onInfoSelect={setInfo}/></section>
  <section className="info-dock">{info==="sand"&&<SandCard beach={beach} t={t}/>} {info==="wave"&&<WaveCard beach={beach} t={t}/>} {info==="jelly"&&<JellyCard beach={beach} t={t} goAid={()=>setInfo("aid")}/>} {info==="shade"&&<ShadeCard beach={beach} lang={lang} t={t}/>} {info==="timer"&&<TimerCard t={t} seconds={seconds} running={running} location={location} begin={begin} toggle={()=>setRunning(!running)} reset={()=>{setSeconds(0);setRunning(false);notified.current=false}}/>} {info==="aid"&&<AidCard/>} {info==="plan"&&<PlanCard beach={beach} lang={lang} t={t}/>}</section>
  <nav className="quick-nav"><button onClick={()=>setInfo("aid")}>✚<span>{t.aid}</span></button><button onClick={()=>setInfo("timer")}>☀<span>{t.timer}</span></button><button onClick={()=>setInfo("plan")}>⌂<span>{t.plan}</span></button></nav>
 </main>
}

function Welcome({lang,setLang,onStart}:{lang:Lang;setLang:(l:Lang)=>void;onStart:()=>void}){const t=labels[lang];return <main className="welcome"><div className="welcome-sun"/><div className="welcome-wave wave-a"/><div className="welcome-wave wave-b"/><section className="welcome-card"><div className="logo-mark">뜨</div><p className="logo-title">뜨바다바</p><p className="logo-sub">뜨거운 바다, 딴 바다로</p><div className="language-box"><h1>{t.choose}</h1><p>{t.sub}</p><div className="language-list">{languageNames.map(l=><button key={l.id} className={lang===l.id?"chosen":""} onClick={()=>setLang(l.id)}><span>{l.native}</span><small>{l.english}</small><b>{lang===l.id?"✓":"›"}</b></button>)}</div><button className="primary wide" onClick={onStart}>{t.start} →</button></div></section></main>}
function RiskPill({risk,t}:{risk:Risk;t:Record<string,string>}){return <em className={`risk ${risk}`}>{t[risk]}</em>}
function SandCard({beach,t}:{beach:Beach;t:Record<string,string>}){const hot=beach.sand>=43;return <div className="detail-card sand-card"><div className="card-icon">🌡️</div><div><p>{t.sand}</p><h2>{beach.sand}<small>°C</small></h2><span>{hot?"맨발 화상 위험이 있어요. 아쿠아슈즈를 신어 주세요.":"모래가 뜨거울 수 있어요. 맨발 이동은 짧게 해주세요."}</span></div><RiskPill risk={hot?"danger":"caution"} t={t}/></div>}
function WaveCard({beach,t}:{beach:Beach;t:Record<string,string>}){const r:Risk=beach.wave>=1.3?"danger":beach.wave>=.8?"caution":"safe";return <div className="detail-card wave-card"><div className="card-icon">🌊</div><div><p>{t.wave}</p><h2>{beach.wave}<small>m</small></h2><span>{r==="danger"?"파도가 높습니다. 입수보다 해변 산책을 추천해요.":"안전요원의 안내 방송을 확인하고 물놀이하세요."}</span></div><RiskPill risk={r} t={t}/></div>}
function JellyCard({beach,t,goAid}:{beach:Beach;t:Record<string,string>;goAid:()=>void}){return <div className="detail-card jelly-card"><div className="card-icon">🪼</div><div><p>{t.jelly} · {beach.jellyArea}</p><h2>{t[beach.jelly]}</h2><span>{beach.jelly==="danger"?"해파리 출몰 위험이 높아 입수를 피해주세요.":"입수 전 안전요원의 해파리 안내를 확인해주세요."}</span></div><RiskPill risk={beach.jelly} t={t}/><button className="mini-action" onClick={goAid}>쏘였을 때 대처법 →</button></div>}
function ShadeCard({beach,lang,t}:{beach:Beach;lang:Lang;t:Record<string,string>}){const title=(index:number)=>lang==="ko"?beach.shade[index].name:`${t.shade} ${index+1}`;const detail=(index:number)=>lang==="ko"?beach.shade[index].detail:`${t.walk} ${beach.shade[index].walk}${t.min}`;return <div className="detail-card shade-card"><div className="card-icon">🌳</div><div className="shade-copy"><p>{t.shade}</p><h2>{title(0)}</h2><span>{detail(0)} · {t.walk} {beach.shade[0].walk}{t.min}</span></div><div className="shade-next"><b>2</b><span>{title(1)}</span><small>{detail(1)} · {t.walk} {beach.shade[1].walk}{t.min}</small></div></div>}
function TimerCard({t,seconds,running,location,begin,toggle,reset}:{t:Record<string,string>;seconds:number;running:boolean;location:string;begin:()=>void;toggle:()=>void;reset:()=>void}){const allow=()=>{"Notification" in window&&Notification.requestPermission()};return <div className="timer-card"><div className="timer-circle" style={{"--progress":`${Math.min(seconds/1200*360,360)}deg`} as React.CSSProperties}><div><small>{t.exposure}</small><b>{fmt(seconds)}</b><span>{seconds<1200?`${t.next} ${Math.ceil((1200-seconds)/60)}${t.min}`:"휴식이 필요해요"}</span></div></div><div><p>☀ {location||"위치를 확인하면 타이머가 시작돼요"}</p>{seconds===0?<button className="primary" onClick={begin}>{t.startTimer}</button>:<button className="primary" onClick={toggle}>{running?"Ⅱ "+t.pause:"▶ "+t.resume}</button>}<button className="ghost" onClick={reset}>{t.reset}</button><button className="notify" onClick={allow}>♢ {t.notify}</button></div></div>}
function AidCard(){const steps=[["01","물 밖으로 이동","환부를 문지르거나 만지지 마세요."],["02","바닷물로 세척","수돗물이나 생수는 사용하지 마세요."],["03","촉수 제거","카드 모서리나 핀셋을 사용하세요."],["04","안전요원 또는 119","호흡곤란·구토가 있으면 바로 신고하세요."]];return <div className="aid-card"><div><span>🪼</span><h2>해파리에 쏘였다면</h2><p>심한 통증이나 전신 증상이 있으면 즉시 119</p></div><ol>{steps.map(s=><li key={s[0]}><b>{s[0]}</b><span><strong>{s[1]}</strong><small>{s[2]}</small></span></li>)}</ol></div>}
type Place={icon:string;name:string;meta:string;image:string};
const NEARBY_PLACES:Record<string,Place[]>={
  haeundae:[{icon:"⛵",name:"더베이101",meta:"해운대 · 해변에서 약 1km",image:"https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?auto=format&fit=crop&w=900&q=80"},{icon:"🌲",name:"동백섬",meta:"해운대 · 산책과 그늘",image:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80"}],
  gwangalli:[{icon:"🌉",name:"민락수변공원",meta:"광안리 · 도보 약 10분",image:"https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=900&q=80"},{icon:"☕",name:"광안리 카페거리",meta:"광안리 · 실내 휴식",image:"https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=900&q=80"}],
  songjeong:[{icon:"🏯",name:"해동용궁사",meta:"송정 · 차로 약 10분",image:"https://images.unsplash.com/photo-1548115184-bc6544d06a58?auto=format&fit=crop&w=900&q=80"},{icon:"🌊",name:"청사포 다릿돌전망대",meta:"송정 · 해안 전망",image:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80"}],
  songdo:[{icon:"🚡",name:"송도해상케이블카",meta:"송도 · 해변 바로 옆",image:"https://images.unsplash.com/photo-1551524164-687a55dd1126?auto=format&fit=crop&w=900&q=80"},{icon:"🌿",name:"암남공원",meta:"송도 · 숲길 산책",image:"https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=900&q=80"}],
  dadaepo:[{icon:"⛲",name:"꿈의 낙조분수",meta:"다대포 · 해변 옆",image:"https://images.unsplash.com/photo-1520637836862-4d197d17c90a?auto=format&fit=crop&w=900&q=80"},{icon:"🌅",name:"다대포 해변공원",meta:"다대포 · 그늘 산책",image:"https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=900&q=80"}],
  ilgwang:[{icon:"🍜",name:"기장시장",meta:"일광 · 차로 약 15분",image:"https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=80"},{icon:"🏖️",name:"일광 해안산책로",meta:"일광 · 해변 인근",image:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80"}],
  imrang:[{icon:"⛪",name:"죽성드림성당",meta:"임랑 · 차로 약 10분",image:"https://images.unsplash.com/photo-1520637836862-4d197d17c90a?auto=format&fit=crop&w=900&q=80"},{icon:"🍜",name:"기장시장",meta:"임랑 · 차로 약 15분",image:"https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=80"}],
};
const PLACE_TRANSLATIONS:Record<string,Record<Exclude<Lang,"ko">,{name:string;meta:string}>>={
  "더베이101":{en:{name:"The Bay 101",meta:"Haeundae · about 1 km"},zh:{name:"The Bay 101",meta:"海云台 · 约1公里"},ja:{name:"The Bay 101",meta:"海雲台 · 約1km"},fr:{name:"The Bay 101",meta:"Haeundae · env. 1 km"}},
  "동백섬":{en:{name:"Dongbaekseom Island",meta:"Haeundae · shaded walk"},zh:{name:"冬柏岛",meta:"海云台 · 林荫步道"},ja:{name:"冬柏島",meta:"海雲台 · 木陰の散策路"},fr:{name:"Île Dongbaekseom",meta:"Haeundae · promenade ombragée"}},
  "민락수변공원":{en:{name:"Millak Waterfront Park",meta:"Gwangalli · 10 min walk"},zh:{name:"民乐水边公园",meta:"广安里 · 步行10分钟"},ja:{name:"民楽水辺公園",meta:"広安里 · 徒歩10分"},fr:{name:"Parc de Millak",meta:"Gwangalli · 10 min à pied"}},
  "광안리 카페거리":{en:{name:"Gwangalli Cafe Street",meta:"Gwangalli · indoor break"},zh:{name:"广安里咖啡街",meta:"广安里 · 室内休息"},ja:{name:"広安里カフェ通り",meta:"広安里 · 屋内休憩"},fr:{name:"Rue des cafés de Gwangalli",meta:"Gwangalli · pause intérieure"}},
  "해동용궁사":{en:{name:"Haedong Yonggungsa",meta:"Songjeong · 10 min by car"},zh:{name:"海东龙宫寺",meta:"松亭 · 车程10分钟"},ja:{name:"海東龍宮寺",meta:"松亭 · 車で10分"},fr:{name:"Temple Haedong Yonggungsa",meta:"Songjeong · 10 min en voiture"}},
  "청사포 다릿돌전망대":{en:{name:"Cheongsapo Observatory",meta:"Songjeong · sea view"},zh:{name:"青沙浦踏石观景台",meta:"松亭 · 海景"},ja:{name:"青沙浦タリットル展望台",meta:"松亭 · 海の眺め"},fr:{name:"Observatoire de Cheongsapo",meta:"Songjeong · vue sur mer"}},
  "송도해상케이블카":{en:{name:"Songdo Marine Cable Car",meta:"Songdo · next to the beach"},zh:{name:"松岛海上缆车",meta:"松岛 · 海滩旁"},ja:{name:"松島海上ケーブルカー",meta:"松島 · ビーチのそば"},fr:{name:"Téléphérique marin de Songdo",meta:"Songdo · près de la plage"}},
  "암남공원":{en:{name:"Amnam Park",meta:"Songdo · forest walk"},zh:{name:"岩南公园",meta:"松岛 · 森林步道"},ja:{name:"岩南公園",meta:"松島 · 森の散策"},fr:{name:"Parc d'Amnam",meta:"Songdo · promenade en forêt"}},
  "꿈의 낙조분수":{en:{name:"Sunset Fountain of Dreams",meta:"Dadaepo · beside the beach"},zh:{name:"梦幻落照喷泉",meta:"多大浦 · 海滩旁"},ja:{name:"夢の落照噴水",meta:"多大浦 · ビーチのそば"},fr:{name:"Fontaine du coucher de soleil",meta:"Dadaepo · près de la plage"}},
  "다대포 해변공원":{en:{name:"Dadaepo Beach Park",meta:"Dadaepo · shaded walk"},zh:{name:"多大浦海滨公园",meta:"多大浦 · 林荫步道"},ja:{name:"多大浦海浜公園",meta:"多大浦 · 木陰の散策"},fr:{name:"Parc de plage de Dadaepo",meta:"Dadaepo · promenade ombragée"}},
  "기장시장":{en:{name:"Gijang Market",meta:"Gijang · 15 min by car"},zh:{name:"机张市场",meta:"机张 · 车程15分钟"},ja:{name:"機張市場",meta:"機張 · 車で15分"},fr:{name:"Marché de Gijang",meta:"Gijang · 15 min en voiture"}},
  "일광 해안산책로":{en:{name:"Ilgwang Coastal Trail",meta:"Ilgwang · near the beach"},zh:{name:"日光海岸步道",meta:"日光 · 海滩附近"},ja:{name:"日光海岸散策路",meta:"日光 · ビーチの近く"},fr:{name:"Sentier côtier d'Ilgwang",meta:"Ilgwang · près de la plage"}},
  "죽성드림성당":{en:{name:"Jukseong Dream Church",meta:"Imrang · 10 min by car"},zh:{name:"竹城梦幻教堂",meta:"林浪 · 车程10分钟"},ja:{name:"竹城ドリーム教会",meta:"林浪 · 車で10分"},fr:{name:"Église de rêve de Jukseong",meta:"Imrang · 10 min en voiture"}},
};
function PlanCard({beach,lang,t}:{beach:Beach;lang:Lang;t:Record<string,string>}){const places=NEARBY_PLACES[beach.id];const [selected,setSelected]=useState<Place|null>(null);useEffect(()=>setSelected(null),[beach.id]);const text=(place:Place)=>lang==="ko"?{name:place.name,meta:place.meta}:PLACE_TRANSLATIONS[place.name][lang];const heading=lang==="ko"?"오늘 바다가 힘들다면":t.plan;return <><div className="plan-card"><div><p>PLAN B, BUSAN</p><h2>{heading}</h2><small style={{fontSize:"8px"}}>{t.tap}</small></div>{places.map(x=>{const copy=text(x);return <button key={x.name} onClick={()=>setSelected(x)} style={{position:"relative",overflow:"hidden"}}><img src={x.image} alt="" style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover",opacity:.48}}/><span style={{position:"relative"}}>{x.icon}</span><b style={{position:"relative",textShadow:"0 1px 3px #000"}}>{copy.name}</b><small style={{position:"relative",textShadow:"0 1px 3px #000"}}>{copy.meta}</small></button>})}</div>{selected&&<PlacePhotoModal place={selected} copy={text(selected)} onClose={()=>setSelected(null)}/>}</>}
function PlacePhotoModal({place,copy,onClose}:{place:Place;copy:{name:string;meta:string};onClose:()=>void}){useEffect(()=>{const close=(event:KeyboardEvent)=>event.key==="Escape"&&onClose();window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[onClose]);return createPortal(<div role="dialog" aria-modal="true" aria-label={copy.name} onClick={onClose} style={{position:"fixed",zIndex:2147483647,inset:0,display:"grid",placeItems:"center",padding:"clamp(16px,4vw,48px)",background:"rgba(5,20,30,.82)",backdropFilter:"blur(7px)"}}><section onClick={e=>e.stopPropagation()} style={{position:"relative",zIndex:1,width:"min(980px,100%)",maxHeight:"92vh",overflow:"hidden",borderRadius:"24px",background:"#fff",boxShadow:"0 28px 100px #000b"}}><img src={place.image} alt={`${copy.name} 사진`} style={{display:"block",width:"100%",height:"min(68vh,650px)",objectFit:"cover"}}/><div style={{padding:"20px 26px 24px"}}><p style={{margin:0,color:"#f36e50",fontSize:"11px",fontWeight:900,letterSpacing:"1px"}}>NEARBY RECOMMENDATION</p><h2 style={{margin:"5px 0",color:"#123d56",fontSize:"clamp(24px,4vw,34px)"}}>{copy.name}</h2><p style={{margin:0,color:"#6f8188",fontSize:"14px"}}>{copy.meta}</p></div><button onClick={onClose} aria-label="닫기" style={{position:"absolute",top:"14px",right:"14px",display:"grid",placeItems:"center",width:"42px",height:"42px",border:0,borderRadius:"50%",background:"#123d56e8",color:"white",fontSize:"25px",cursor:"pointer"}}>×</button></section></div>,document.body)}
