"use client";

import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import BeachMap from "./BeachMap";

type Lang = "ko" | "en" | "zh" | "ja" | "fr";
type InfoKind = "sand" | "wave" | "jelly" | "shade" | "timer" | "aid" | "plan";
type Risk = "safe" | "caution" | "danger";
type JellyRisk = Risk | "unknown";

type Beach = { id:string; ko:string; en:string; displayName?:string; localizedJellyArea?:string; district:string; coordinate:[number,number]; sand:number|null; wave:number|null; jelly:JellyRisk; jellyPresent:boolean; jellyArea:string; observedAt?:string|null; waveStation?:string; marineSource?:string; shade:{name:string; detail:string; walk:number}[] };
type MarineObservation = { sand:{temperature:number|null;status:string;source:string};wave:{height:number|null;observedAt:string|null;station:string;source:string;configured:boolean};jellyfish:{risk:JellyRisk;present:boolean;area:string;reportDate:string|null;reportTitle:string|null;source:string;sourceUrl:string} };
const beaches:Beach[] = [
  {id:"haeundae",ko:"해운대",en:"Haeundae",district:"해운대구",coordinate:[35.1587,129.1604],sand:null,wave:null,jelly:"unknown",jellyPresent:false,jellyArea:"",shade:[{name:"해운대 광장 그늘막",detail:"5번 망루 뒤편",walk:2},{name:"동백섬 산책로",detail:"수목 그늘 구간",walk:7}]},
  {id:"gwangalli",ko:"광안리",en:"Gwangalli",district:"수영구",coordinate:[35.1531,129.1186],sand:null,wave:null,jelly:"unknown",jellyPresent:false,jellyArea:"",shade:[{name:"만남의 광장",detail:"중앙 음수대 옆",walk:3},{name:"민락수변공원",detail:"해변 북쪽 수목",walk:8}]},
  {id:"songjeong",ko:"송정",en:"Songjeong",district:"해운대구",coordinate:[35.1798,129.1997],sand:null,wave:null,jelly:"unknown",jellyPresent:false,jellyArea:"",shade:[{name:"죽도공원 입구",detail:"송일정 아래",walk:5},{name:"중앙 안내소",detail:"3번 망루 맞은편",walk:2}]},
  {id:"songdo",ko:"송도",en:"Songdo",district:"서구",coordinate:[35.0765,129.0172],sand:null,wave:null,jelly:"unknown",jellyPresent:false,jellyArea:"",shade:[{name:"송림공원",detail:"케이블카 하부",walk:4},{name:"분수광장 차양",detail:"중앙 안내소 옆",walk:2}]},
  {id:"dadaepo",ko:"다대포",en:"Dadaepo",district:"사하구",coordinate:[35.0483,128.9652],sand:null,wave:null,jelly:"unknown",jellyPresent:false,jellyArea:"",shade:[{name:"해변공원 소나무숲",detail:"낙조분수 서편",walk:5},{name:"생태탐방로 쉼터",detail:"고우니길 2번 데크",walk:9}]},
  {id:"ilgwang",ko:"일광",en:"Ilgwang",district:"기장군",coordinate:[35.2633,129.2338],sand:null,wave:null,jelly:"unknown",jellyPresent:false,jellyArea:"",shade:[{name:"이천쉼터",detail:"해변 남쪽 산책로",walk:8},{name:"중앙 안내소 차양",detail:"해변 진입광장",walk:2}]},
  {id:"imrang",ko:"임랑",en:"Imrang",district:"기장군",coordinate:[35.3197,129.2659],sand:null,wave:null,jelly:"unknown",jellyPresent:false,jellyArea:"",shade:[{name:"임랑행정봉사실",detail:"해변 중앙 쉼터",walk:3},{name:"임랑공원 수목",detail:"주차장 맞은편",walk:6}]},
];
const languageNames:{id:Lang; native:string; english:string}[]=[{id:"ko",native:"한국어",english:"Korean"},{id:"en",native:"English",english:"English"},{id:"zh",native:"中文",english:"Chinese"},{id:"ja",native:"日本語",english:"Japanese"},{id:"fr",native:"Français",english:"French"}];
const languageLabels:Record<Lang,Record<Lang,string>>={
  ko:{ko:"한국어",en:"영어",zh:"중국어",ja:"일본어",fr:"프랑스어"},en:{ko:"Korean",en:"English",zh:"Chinese",ja:"Japanese",fr:"French"},zh:{ko:"韩语",en:"英语",zh:"中文",ja:"日语",fr:"法语"},ja:{ko:"韓国語",en:"英語",zh:"中国語",ja:"日本語",fr:"フランス語"},fr:{ko:"Coréen",en:"Anglais",zh:"Chinois",ja:"Japonais",fr:"Français"},
};
const labels:Record<Lang,Record<string,string>>={
  ko:{choose:"언어를 선택해 주세요",sub:"부산 바다를 더 안전하고 시원하게 즐겨요",start:"지도 열기",guide:"부산 해수욕장 안전 지도",change:"언어",tap:"지도 위 아이콘을 눌러 자세한 정보를 확인하세요",sand:"모래 온도",wave:"파도 높이",jelly:"해파리",shade:"그늘",timer:"햇빛 타이머",aid:"응급처치",plan:"다른 활동",myLocation:"내 위치",placePhoto:"장소 사진",photoLoading:"공개 장소 사진 불러오는 중…",photoUnavailable:"공개 사진을 찾지 못했어요",photoBy:"출처:",safe:"안전",caution:"주의",danger:"위험",walk:"도보",min:"분",startTimer:"위치 확인 후 시작",pause:"잠시 멈춤",resume:"다시 시작",reset:"초기화",notify:"알림 허용",exposure:"노출 시간",next:"다음 알림"},
  en:{choose:"Choose your language",sub:"Enjoy Busan's beaches safely and comfortably",start:"Open map",guide:"Busan beach safety map",change:"Language",tap:"Tap an icon on the map for details",sand:"Sand temperature",wave:"Wave height",jelly:"Jellyfish",shade:"Shade",timer:"Sun timer",aid:"First aid",plan:"Other plans",myLocation:"My location",placePhoto:"place photo",photoLoading:"Loading a public place photo…",photoUnavailable:"No public photo found",photoBy:"Source:",safe:"Safe",caution:"Caution",danger:"Danger",walk:"Walk",min:"min",startTimer:"Locate & start",pause:"Pause",resume:"Resume",reset:"Reset",notify:"Allow alerts",exposure:"Exposure",next:"Next alert"},
  zh:{choose:"请选择语言",sub:"更安全、更舒适地享受釜山海滩",start:"打开地图",guide:"釜山海滩安全地图",change:"语言",tap:"点击地图图标查看详细信息",sand:"沙温",wave:"浪高",jelly:"水母",shade:"阴凉",timer:"日晒计时",aid:"急救",plan:"其他活动",myLocation:"我的位置",placePhoto:"地点照片",photoLoading:"正在加载公开地点照片…",photoUnavailable:"未找到公开照片",photoBy:"来源：",safe:"安全",caution:"注意",danger:"危险",walk:"步行",min:"分钟",startTimer:"定位并开始",pause:"暂停",resume:"继续",reset:"重置",notify:"允许通知",exposure:"暴露时间",next:"下次提醒"},
  ja:{choose:"言語を選択してください",sub:"釜山の海を安全で快適に楽しもう",start:"地図を開く",guide:"釜山ビーチ安全マップ",change:"言語",tap:"地図上のアイコンを押して詳細を確認",sand:"砂の温度",wave:"波の高さ",jelly:"クラゲ",shade:"日陰",timer:"日光タイマー",aid:"応急処置",plan:"別の活動",myLocation:"現在地",placePhoto:"場所の写真",photoLoading:"公開されている場所の写真を読み込み中…",photoUnavailable:"公開写真が見つかりません",photoBy:"出典：",safe:"安全",caution:"注意",danger:"危険",walk:"徒歩",min:"分",startTimer:"位置確認して開始",pause:"一時停止",resume:"再開",reset:"リセット",notify:"通知を許可",exposure:"経過時間",next:"次の通知"},
  fr:{choose:"Choisissez votre langue",sub:"Profitez des plages de Busan en toute sécurité",start:"Ouvrir la carte",guide:"Carte sécurité des plages de Busan",change:"Langue",tap:"Touchez une icône sur la carte pour les détails",sand:"Température du sable",wave:"Hauteur des vagues",jelly:"Méduses",shade:"Ombre",timer:"Minuteur solaire",aid:"Premiers soins",plan:"Autres activités",myLocation:"Ma position",placePhoto:"photo du lieu",photoLoading:"Chargement d’une photo publique…",photoUnavailable:"Aucune photo publique trouvée",photoBy:"Source :",safe:"Sûr",caution:"Prudence",danger:"Danger",walk:"À pied",min:"min",startTimer:"Localiser et démarrer",pause:"Pause",resume:"Reprendre",reset:"Réinitialiser",notify:"Activer alertes",exposure:"Exposition",next:"Prochaine alerte"},
};
const ui:Record<Lang,Record<string,string>>={
  ko:{logo:"뜨",second:"초",appName:"뜨바다바",tagline:"뜨거운 바다, 딴 바다로",mapTitle:"부산 해수욕장 지도",beachWord:"해수욕장",demo:"부산 현재 시각",regularOpen:"일반 영업시간상 영업 중",locationChecking:"위치 확인 중…",timerStarted:"타이머 시작됨",locationConfirmed:"인근 · 위치 확인됨",timerNoGps:"위치 권한 없이 타이머 시작됨",timerAlert:"10초 동안 햇빛에 노출되었어요. 그늘에서 쉬어 주세요.",actualMap:"실제 지도",beachMarker:"해수욕장",nearbyRecommendation:"주변 추천 장소",close:"닫기",photo:"사진"},
  en:{logo:"T",second:"sec",appName:"Tteubadaba",tagline:"Hot sea? Choose another sea",mapTitle:"Busan Beach Map",beachWord:"Beach",demo:"Current Busan time",regularOpen:"Open during regular hours",locationChecking:"Checking location…",timerStarted:"Timer started",locationConfirmed:"nearby · Location confirmed",timerNoGps:"Timer started without location access",timerAlert:"You have been in the sun for 10 seconds. Please rest in the shade.",actualMap:"live map",beachMarker:"Beach",nearbyRecommendation:"NEARBY RECOMMENDATION",close:"Close",photo:"photo"},
  zh:{logo:"热",second:"秒",appName:"热海转身",tagline:"海水太热，就去另一片海",mapTitle:"釜山海滩地图",beachWord:"海滩",demo:"釜山当前时间",regularOpen:"按正常营业时间开放",locationChecking:"正在确认位置…",timerStarted:"计时器已启动",locationConfirmed:"附近 · 已确认位置",timerNoGps:"未使用位置权限，计时器已启动",timerAlert:"您已在阳光下暴露10秒，请到阴凉处休息。",actualMap:"实时地图",beachMarker:"海滩",nearbyRecommendation:"附近推荐地点",close:"关闭",photo:"照片"},
  ja:{logo:"ト",second:"秒",appName:"トゥバダバ",tagline:"熱い海から、別の海へ",mapTitle:"釜山ビーチマップ",beachWord:"ビーチ",demo:"釜山の現在時刻",regularOpen:"通常営業時間内で営業中",locationChecking:"位置情報を確認中…",timerStarted:"タイマーを開始しました",locationConfirmed:"周辺 · 位置確認済み",timerNoGps:"位置情報なしでタイマーを開始しました",timerAlert:"日光に10秒間当たりました。日陰で休んでください。",actualMap:"リアルマップ",beachMarker:"ビーチ",nearbyRecommendation:"周辺のおすすめ",close:"閉じる",photo:"写真"},
  fr:{logo:"T",second:"s",appName:"Tteubadaba",tagline:"Mer trop chaude ? Changez de plage",mapTitle:"Carte des plages de Busan",beachWord:"Plage",demo:"Heure actuelle à Busan",regularOpen:"Ouvert selon les horaires habituels",locationChecking:"Localisation en cours…",timerStarted:"Minuteur démarré",locationConfirmed:"à proximité · Position confirmée",timerNoGps:"Minuteur démarré sans localisation",timerAlert:"Vous êtes au soleil depuis 10 secondes. Reposez-vous à l’ombre.",actualMap:"carte réelle",beachMarker:"Plage",nearbyRecommendation:"RECOMMANDATION À PROXIMITÉ",close:"Fermer",photo:"photo"},
};
const beachNames:Record<Lang,Record<string,string>>={
  ko:{haeundae:"해운대",gwangalli:"광안리",songjeong:"송정",songdo:"송도",dadaepo:"다대포",ilgwang:"일광",imrang:"임랑"},
  en:{haeundae:"Haeundae",gwangalli:"Gwangalli",songjeong:"Songjeong",songdo:"Songdo",dadaepo:"Dadaepo",ilgwang:"Ilgwang",imrang:"Imrang"},
  zh:{haeundae:"海云台",gwangalli:"广安里",songjeong:"松亭",songdo:"松岛",dadaepo:"多大浦",ilgwang:"日光",imrang:"林浪"},
  ja:{haeundae:"海雲台",gwangalli:"広安里",songjeong:"松亭",songdo:"松島",dadaepo:"多大浦",ilgwang:"日光",imrang:"林浪"},
  fr:{haeundae:"Haeundae",gwangalli:"Gwangalli",songjeong:"Songjeong",songdo:"Songdo",dadaepo:"Dadaepo",ilgwang:"Ilgwang",imrang:"Imrang"},
};
const aidCopy:Record<Lang,{title:string;sub:string;steps:[string,string][]}>={
  ko:{title:"해파리에 쏘였다면",sub:"심한 통증이나 전신 증상이 있으면 즉시 119",steps:[["물 밖으로 이동","환부를 문지르거나 만지지 마세요."],["바닷물로 세척","수돗물이나 생수는 사용하지 마세요."],["촉수 제거","카드 모서리나 핀셋을 사용하세요."],["안전요원 또는 119","호흡곤란·구토가 있으면 바로 신고하세요."]]},
  en:{title:"If stung by a jellyfish",sub:"Call 119 for severe pain or whole-body symptoms",steps:[["Leave the water","Do not rub or touch the affected area."],["Rinse with seawater","Do not use tap or bottled water."],["Remove tentacles","Use a card edge or tweezers."],["Lifeguard or 119","Call immediately for breathing trouble or vomiting."]]},
  zh:{title:"被水母蜇伤时",sub:"剧痛或全身症状时请立即拨打119",steps:[["离开水面","不要揉搓或触碰患处。"],["用海水冲洗","不要使用自来水或瓶装水。"],["去除触手","使用卡片边缘或镊子。"],["救生员或119","呼吸困难或呕吐时立即求助。"]]},
  ja:{title:"クラゲに刺されたら",sub:"激しい痛みや全身症状があれば直ちに119へ",steps:[["水から上がる","患部をこすったり触ったりしないでください。"],["海水で洗う","水道水や飲料水は使わないでください。"],["触手を除去","カードの縁やピンセットを使ってください。"],["監視員または119","呼吸困難や嘔吐があれば直ちに連絡してください。"]]},
  fr:{title:"En cas de piqûre de méduse",sub:"Appelez le 119 en cas de douleur intense ou de symptômes généraux",steps:[["Sortez de l’eau","Ne frottez pas et ne touchez pas la zone."],["Rincez à l’eau de mer","N’utilisez ni eau du robinet ni eau en bouteille."],["Retirez les tentacules","Utilisez le bord d’une carte ou une pince."],["Sauveteur ou 119","Appelez immédiatement en cas de gêne respiratoire ou vomissements."]]},
};
const sunCareCopy:Record<Lang,{eyebrow:string;title:string;intro:string;steps:[string,string][];urgent:string;note:string;close:string}>={
  ko:{eyebrow:"햇빛 노출 알림",title:"이제 그늘에서 쉬어주세요",intro:"강한 자외선에 오래 노출되면 일광화상, 피부 벗겨짐·물집이 생길 수 있고 반복될수록 피부암 위험도 높아질 수 있어요.",steps:[["햇빛 피하기","그늘이나 실내로 이동하고 피부를 옷으로 가려주세요."],["피부 식히기","시원한 샤워나 젖은 수건을 사용하고 얼음을 직접 대지 마세요."],["수분·보습","물을 충분히 마시고 무향 보습제나 알로에를 발라주세요."],["물집 보호","물집을 터뜨리거나 벗겨지는 피부를 뜯지 마세요."]],urgent:"넓은 물집·심한 부기, 고열, 어지럼, 메스꺼움 또는 심한 두통이 있으면 의료진의 도움을 받거나 119에 연락하세요.",note:"현재 10초 타이머는 기능 확인용입니다. 실제 위험은 자외선 지수, 시간대, 피부 상태와 노출 시간에 따라 달라집니다.",close:"확인했어요"},
  en:{eyebrow:"SUN EXPOSURE ALERT",title:"It is time to rest in the shade",intro:"Long exposure to strong UV can cause sunburn, peeling and blisters. Repeated sunburns can also increase skin-cancer risk.",steps:[["Leave the sun","Move indoors or into shade and cover exposed skin."],["Cool your skin","Use a cool shower or damp towel. Do not apply ice directly."],["Hydrate and moisturize","Drink water and apply an unperfumed moisturizer or aloe."],["Protect blisters","Do not pop blisters or pull peeling skin."]],urgent:"Get medical help for widespread blisters, severe swelling, high fever, dizziness, nausea or a severe headache. Call 119 in an emergency.",note:"This 10-second timer is a feature demonstration. Real risk varies with UV level, time of day, skin and exposure duration.",close:"Got it"},
  zh:{eyebrow:"日晒提醒",title:"现在请到阴凉处休息",intro:"长时间暴露在强紫外线下可能造成晒伤、脱皮和水疱，反复晒伤还可能增加皮肤癌风险。",steps:[["避开阳光","进入室内或阴凉处，并用衣物遮盖皮肤。"],["给皮肤降温","使用凉水淋浴或湿毛巾，不要把冰直接敷在皮肤上。"],["补水与保湿","多喝水，并涂抹无香保湿霜或芦荟。"],["保护水疱","不要弄破水疱，也不要撕扯脱皮。"]],urgent:"如出现大面积水疱、严重肿胀、高烧、头晕、恶心或剧烈头痛，请就医；紧急情况请拨打119。",note:"当前10秒计时器用于功能演示。实际风险会因紫外线指数、时段、皮肤状态和暴露时间而不同。",close:"知道了"},
  ja:{eyebrow:"日光曝露アラート",title:"日陰で休む時間です",intro:"強い紫外線を長時間浴びると、日焼け、皮むけ、水ぶくれが起こり、繰り返すと皮膚がんのリスクも高まります。",steps:[["日光を避ける","屋内か日陰へ移動し、露出した皮膚を衣服で覆ってください。"],["皮膚を冷やす","冷たいシャワーや濡れタオルを使い、氷を直接当てないでください。"],["水分・保湿","水を十分に飲み、無香料の保湿剤やアロエを塗ってください。"],["水ぶくれを守る","水ぶくれを潰したり、むけた皮を剥がしたりしないでください。"]],urgent:"広範囲の水ぶくれ、強い腫れ、高熱、めまい、吐き気、激しい頭痛がある場合は受診し、緊急時は119へ連絡してください。",note:"現在の10秒タイマーは機能確認用です。実際の危険度は紫外線指数、時間帯、肌の状態、曝露時間によって異なります。",close:"確認しました"},
  fr:{eyebrow:"ALERTE D’EXPOSITION",title:"Il est temps de vous reposer à l’ombre",intro:"Une forte exposition aux UV peut provoquer coups de soleil, peau qui pèle et cloques. Des coups de soleil répétés augmentent aussi le risque de cancer de la peau.",steps:[["Quittez le soleil","Allez à l’intérieur ou à l’ombre et couvrez la peau exposée."],["Rafraîchissez la peau","Prenez une douche fraîche ou utilisez une serviette humide, sans glace directe."],["Hydratez et apaisez","Buvez de l’eau et appliquez un hydratant sans parfum ou de l’aloe vera."],["Protégez les cloques","Ne percez pas les cloques et n’arrachez pas la peau qui pèle."]],urgent:"Consultez en cas de cloques étendues, fort gonflement, forte fièvre, vertiges, nausées ou mal de tête intense. Appelez le 119 en urgence.",note:"Ce minuteur de 10 secondes sert de démonstration. Le risque réel dépend de l’indice UV, de l’heure, de la peau et de la durée d’exposition.",close:"J’ai compris"},
};

const copy:Record<Lang,Record<string,string>>={
  ko:{sandHot:"맨발 화상 위험이 있어요. 아쿠아슈즈를 신어 주세요.",sand:"모래가 뜨거울 수 있어요. 맨발 이동은 짧게 해주세요.",waveDanger:"파도가 높습니다. 입수보다 해변 산책을 추천해요.",wave:"안전요원의 안내 방송을 확인하고 물놀이하세요.",jellyDanger:"해파리 출몰 위험이 높아 입수를 피해주세요.",jelly:"입수 전 안전요원의 해파리 안내를 확인해주세요.",jellyAid:"쏘였을 때 대처법 →",rest:"휴식이 필요해요",location:"위치를 확인하면 타이머가 시작돼요",aidTitle:"해파리에 쏘였다면",aidSub:"심한 통증이나 전신 증상이 있으면 즉시 119"},
  en:{sandHot:"Hot sand can burn bare feet. Please wear water shoes.",sand:"The sand may be hot. Keep barefoot walks short.",waveDanger:"Waves are high. A beach walk is safer than entering the water.",wave:"Check the lifeguard announcements before swimming.",jellyDanger:"High jellyfish risk. Please avoid entering the water.",jelly:"Check the lifeguard's jellyfish notice before swimming.",jellyAid:"What to do after a sting →",rest:"Time for a break",location:"The timer starts after location is checked",aidTitle:"If you are stung by a jellyfish",aidSub:"Call 119 immediately for severe pain or whole-body symptoms"},
  zh:{sandHot:"沙子很烫，可能灼伤赤脚。请穿水鞋。",sand:"沙子可能很烫，请缩短赤脚行走时间。",waveDanger:"浪很高，建议在海边散步，不要下水。",wave:"下水前请确认救生员的广播。",jellyDanger:"水母出没风险高，请避免下水。",jelly:"下水前请确认救生员的水母提示。",jellyAid:"被蜇后的处理方法 →",rest:"需要休息了",location:"确认位置后开始计时",aidTitle:"被水母蜇伤时",aidSub:"剧痛或全身症状时请立即拨打119"},
  ja:{sandHot:"砂が熱く、裸足ではやけどのおそれがあります。",sand:"砂が熱いことがあります。裸足での移動は短くしてください。",waveDanger:"波が高いです。入水より浜辺の散歩がおすすめです。",wave:"入水前にライフガードの案内を確認してください。",jellyDanger:"クラゲ出没の危険が高いため、入水を避けてください。",jelly:"入水前にクラゲ情報を確認してください。",jellyAid:"刺されたときの対処法 →",rest:"休憩が必要です",location:"位置確認後にタイマーが始まります",aidTitle:"クラゲに刺されたら",aidSub:"激しい痛みや全身症状があれば直ちに119へ"},
  fr:{sandHot:"Le sable chaud peut brûler les pieds nus. Portez des chaussures d'eau.",sand:"Le sable peut être chaud. Limitez la marche pieds nus.",waveDanger:"Les vagues sont hautes. Préférez une promenade sur la plage.",wave:"Vérifiez les annonces des sauveteurs avant de vous baigner.",jellyDanger:"Risque élevé de méduses : évitez de vous baigner.",jelly:"Vérifiez les informations sur les méduses avant de vous baigner.",jellyAid:"Que faire après une piqûre →",rest:"Il est temps de faire une pause",location:"Le minuteur démarre après la localisation",aidTitle:"En cas de piqûre de méduse",aidSub:"Appelez immédiatement le 119 en cas de douleur intense ou de symptômes généraux"}
};
const langOf=(t:Record<string,string>):Lang=>(Object.keys(labels) as Lang[]).find(key=>labels[key]===t)??"ko";
const textOf=(t:Record<string,string>,key:string)=>copy[langOf(t)][key];
const marineCopy:Record<Lang,{noData:string;official:string;noJelly:string;reported:(district:string)=>string;sandUnavailable:string;waveUnavailable:string;waveStation:(station:string)=>string}>={
  ko:{noData:"자료 없음",official:"공식 자료",noJelly:"최신 공식 보고서에 출현 보고 없음",reported:district=>`${district} 출현 보고`,sandUnavailable:"공식 실시간 모래 표면온도 관측자료가 없습니다.",waveUnavailable:"최신 파고 관측값을 불러오지 못했습니다.",waveStation:station=>`${station} 관측값`},
  en:{noData:"No data",official:"Official data",noJelly:"No sighting in the latest official report",reported:district=>`Reported in ${district}`,sandUnavailable:"No official real-time sand-surface observation is available.",waveUnavailable:"The latest observed wave height is unavailable.",waveStation:station=>`Observed at ${station}`},
  zh:{noData:"暂无数据",official:"官方数据",noJelly:"最新官方报告中无出没记录",reported:district=>`${district}有出没报告`,sandUnavailable:"暂无官方实时沙面温度观测数据。",waveUnavailable:"无法获取最新浪高观测值。",waveStation:station=>`${station}观测值`},
  ja:{noData:"データなし",official:"公式データ",noJelly:"最新の公式報告に出現情報なし",reported:district=>`${district}で出現報告`,sandUnavailable:"砂面温度の公式リアルタイム観測データはありません。",waveUnavailable:"最新の波高観測値を取得できません。",waveStation:station=>`${station}の観測値`},
  fr:{noData:"Aucune donnée",official:"Données officielles",noJelly:"Aucun signalement dans le dernier rapport officiel",reported:district=>`Signalement à ${district}`,sandUnavailable:"Aucune mesure officielle en temps réel de la surface du sable n’est disponible.",waveUnavailable:"La dernière hauteur de vague observée est indisponible.",waveStation:station=>`Mesure de ${station}`},
};
const districtNames:Record<Lang,Record<string,string>>={
  ko:{해운대구:"해운대구",수영구:"수영구",서구:"서구",사하구:"사하구",기장군:"기장군"},
  en:{해운대구:"Haeundae-gu",수영구:"Suyeong-gu",서구:"Seo-gu",사하구:"Saha-gu",기장군:"Gijang-gun"},
  zh:{해운대구:"海云台区",수영구:"水营区",서구:"西区",사하구:"沙下区",기장군:"机张郡"},
  ja:{해운대구:"海雲台区",수영구:"水営区",서구:"西区",사하구:"沙下区",기장군:"機張郡"},
  fr:{해운대구:"Haeundae-gu",수영구:"Suyeong-gu",서구:"Seo-gu",사하구:"Saha-gu",기장군:"Gijang-gun"},
};
const riskOf=(b:Beach):Risk=>b.jelly==="danger"||(b.wave!==null&&b.wave>=1.3)?"danger":(b.sand!==null&&b.sand>=42)||(b.wave!==null&&b.wave>=.8)||b.jelly==="caution"?"caution":"safe";
const fmt=(s:number)=>`${Math.floor(s/60).toString().padStart(2,"0")}:${(s%60).toString().padStart(2,"0")}`;
const timeLocales:Record<Lang,string>={ko:"ko-KR",en:"en-US",zh:"zh-CN",ja:"ja-JP",fr:"fr-FR"};
const formatBusanTime=(date:Date,lang:Lang)=>new Intl.DateTimeFormat(timeLocales[lang],{timeZone:"Asia/Seoul",month:"short",day:"numeric",weekday:"short",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(date);
function playSunAlarm(context:AudioContext|null){if(!context)return;void context.resume().then(()=>{const start=context.currentTime;[0,.24,.48,.78].forEach((offset,index)=>{const oscillator=context.createOscillator(),gain=context.createGain(),at=start+offset;oscillator.type="sine";oscillator.frequency.setValueAtTime(index===3?1046:880,at);gain.gain.setValueAtTime(.0001,at);gain.gain.exponentialRampToValueAtTime(.24,at+.025);gain.gain.exponentialRampToValueAtTime(.0001,at+.18);oscillator.connect(gain).connect(context.destination);oscillator.start(at);oscillator.stop(at+.2)})}).catch(()=>{})}

export default function Home(){
 const [lang,setLang]=useState<Lang>("ko"),[entered,setEntered]=useState(false),[beachId,setBeachId]=useState("haeundae"),[info,setInfo]=useState<InfoKind>("sand"),[seconds,setSeconds]=useState(0),[running,setRunning]=useState(false),[location,setLocation]=useState("");
 const [userPosition,setUserPosition]=useState<[number,number]|null>(null),[recommendedPlaces,setRecommendedPlaces]=useState<AiPlace[]>([]),[sunCareOpen,setSunCareOpen]=useState(false),[now,setNow]=useState<Date|null>(null);
 const [marine,setMarine]=useState<Record<string,MarineObservation>>({});
 const notified=useRef(false),audioContext=useRef<AudioContext|null>(null),t=labels[lang],u=ui[lang];
 const liveBeaches=beaches.map(item=>{const observation=marine[item.id];return observation?{...item,sand:observation.sand.temperature,wave:observation.wave.height,jelly:observation.jellyfish.risk,jellyPresent:observation.jellyfish.present,jellyArea:observation.jellyfish.area,observedAt:observation.wave.observedAt,waveStation:observation.wave.station,marineSource:observation.jellyfish.source}:item});
 const beach=liveBeaches.find(b=>b.id===beachId)??liveBeaches[0];
 const localizedBeaches=liveBeaches.map(item=>({...item,displayName:beachNames[lang][item.id],localizedJellyArea:item.jellyPresent?marineCopy[lang].reported(districtNames[lang][item.district]??item.district):marineCopy[lang].noJelly}));
 const localizedBeach=localizedBeaches.find(item=>item.id===beachId)??localizedBeaches[0],beachName=beachNames[lang][beach.id];
 useEffect(()=>{document.documentElement.lang=lang;document.title=`${u.appName} · ${u.mapTitle}`},[lang,u.appName,u.mapTitle]);
 useEffect(()=>{setNow(new Date());const clock=window.setInterval(()=>setNow(new Date()),30000);return()=>window.clearInterval(clock)},[]);
 useEffect(()=>{const controller=new AbortController();const base=window.location.hostname.endsWith("github.io")?"https://tteubadaba-busan.vercel.app":"";Promise.all(beaches.map(async item=>{try{const response=await fetch(`${base}/api/marine?beach=${item.id}`,{signal:controller.signal});if(!response.ok)return;const data=await response.json() as MarineObservation;setMarine(current=>({...current,[item.id]:data}))}catch(error){if((error as Error).name!=="AbortError")console.warn("Official marine data unavailable",item.id)}}));return()=>controller.abort()},[]);
 useEffect(()=>{if(!running)return;const i=window.setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(i)},[running]);
 useEffect(()=>{if(seconds>=10&&!notified.current){notified.current=true;setRunning(false);setSunCareOpen(true);playSunAlarm(audioContext.current);if("Notification" in window&&Notification.permission==="granted")new Notification(u.appName,{body:u.timerAlert})}},[seconds,lang]);
 useEffect(()=>{setRecommendedPlaces([])},[beachId]);
 const begin=()=>{if(!audioContext.current)audioContext.current=new AudioContext();void audioContext.current.resume();setSunCareOpen(false);setLocation(u.locationChecking);if(!navigator.geolocation){setLocation(u.timerStarted);setRunning(true);return}navigator.geolocation.getCurrentPosition(()=>{setLocation(`${beachName} ${u.locationConfirmed}`);setRunning(true)},()=>{setLocation(u.timerNoGps);setRunning(true)},{timeout:6000})};
 const selectBeach=(id:string)=>{setRecommendedPlaces([]);setBeachId(id);if(userPosition)setInfo("plan")};
 if(!entered)return <Welcome lang={lang} setLang={next=>{setLang(next);setLocation("")}} onStart={()=>setEntered(true)}/>;
 return <><main className="map-app"><header className="map-header"><button className="brand" onClick={()=>setInfo("sand")}><span className="logo-mini">{u.logo}</span><span>{u.appName}<small>{u.tagline}</small></span></button><p><i/> {t.guide}</p><button className="language-button" onClick={()=>setEntered(false)}>文 {t.change}</button></header>
  <section className="map-toolbar"><div className="beach-tabs">{liveBeaches.map(b=><button key={b.id} className={b.id===beachId?"active":""} onClick={()=>selectBeach(b.id)}><i className={riskOf(b)}/>{beachNames[lang][b.id]}</button>)}</div><small>● {u.demo} · {now?formatBusanTime(now,lang):"--:--"}</small></section>
  <section className="map-stage"><div className="map-title"><p>{u.mapTitle}</p><h1>{beachName} <span>{u.beachWord}</span></h1><small>{t.tap}</small></div><BeachMap beach={localizedBeach} beaches={localizedBeaches} labels={{...t,...u}} activeInfo={info} userPosition={userPosition} recommendedPlaces={recommendedPlaces} onBeachSelect={selectBeach} onInfoSelect={setInfo}/></section>
  <section className="info-dock">{info==="sand"&&<SandCard beach={beach} t={t}/>} {info==="wave"&&<WaveCard beach={beach} t={t}/>} {info==="jelly"&&<JellyCard beach={localizedBeach} t={t} goAid={()=>setInfo("aid")}/>} {info==="shade"&&<ShadeCard beach={beach} lang={lang} t={t}/>} {info==="timer"&&<TimerCard t={t} secondLabel={u.second} seconds={seconds} running={running} location={location} begin={begin} toggle={()=>setRunning(!running)} reset={()=>{setSeconds(0);setRunning(false);setSunCareOpen(false);notified.current=false}}/>} {info==="aid"&&<AidCard lang={lang}/>} {info==="plan"&&<PlanCard beach={beach} lang={lang} t={t} currentResults={recommendedPlaces} onLocated={setUserPosition} onResults={setRecommendedPlaces}/>}</section>
  <nav className="quick-nav"><button onClick={()=>setInfo("timer")}>☀<span>{t.timer}</span></button><button onClick={()=>setInfo("plan")}>⌂<span>{t.plan}</span></button></nav>
 </main>{sunCareOpen&&<SunCareModal lang={lang} onClose={()=>setSunCareOpen(false)}/>}</>
}

function Welcome({lang,setLang,onStart}:{lang:Lang;setLang:(l:Lang)=>void;onStart:()=>void}){const t=labels[lang],u=ui[lang];return <main className="welcome"><div className="welcome-sun"/><div className="welcome-wave wave-a"/><div className="welcome-wave wave-b"/><section className="welcome-card"><div className="logo-mark">{u.logo}</div><p className="logo-title">{u.appName}</p><p className="logo-sub">{u.tagline}</p><div className="language-box"><h1>{t.choose}</h1><p>{t.sub}</p><div className="language-list">{languageNames.map(l=><button key={l.id} className={lang===l.id?"chosen":""} onClick={()=>setLang(l.id)}><span>{l.native}</span><small>{languageLabels[lang][l.id]}</small><b>{lang===l.id?"✓":"›"}</b></button>)}</div><button className="primary wide" onClick={onStart}>{t.start} →</button></div></section></main>}
function SunCareModal({lang,onClose}:{lang:Lang;onClose:()=>void}){const content=sunCareCopy[lang],sourceLabel={ko:"의학 정보 출처",en:"Medical sources",zh:"医学信息来源",ja:"医療情報の出典",fr:"Sources médicales"}[lang];useEffect(()=>{const close=(event:KeyboardEvent)=>event.key==="Escape"&&onClose();window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[onClose]);return createPortal(<div className="sun-care-overlay" role="alertdialog" aria-modal="true" aria-labelledby="sun-care-title" onClick={onClose}><section className="sun-care-modal" onClick={event=>event.stopPropagation()}><button className="sun-care-x" onClick={onClose} aria-label={ui[lang].close}>×</button><div className="sun-care-heading"><span>☀️</span><div><p>{content.eyebrow}</p><h2 id="sun-care-title">{content.title}</h2></div></div><p className="sun-care-intro">{content.intro}</p><ol>{content.steps.map((step,index)=><li key={step[0]}><b>{index+1}</b><div><strong>{step[0]}</strong><span>{step[1]}</span></div></li>)}</ol><div className="sun-care-urgent"><b>!</b><span>{content.urgent}</span></div><p className="sun-care-note">{content.note}</p><small className="sun-care-sources">{sourceLabel}: <a href="https://www.cdc.gov/skin-cancer/prevention/sunburn.html" target="_blank" rel="noreferrer">CDC</a> · <a href="https://www.aad.org/public/everyday-care/injured-skin/burns/treat-sunburn" target="_blank" rel="noreferrer">AAD</a></small><button className="primary sun-care-close" onClick={onClose}>{content.close}</button></section></div>,document.body)}
function RiskPill({risk,t}:{risk:Risk;t:Record<string,string>}){return <em className={`risk ${risk}`}>{t[risk]}</em>}
function SandCard({beach,t}:{beach:Beach;t:Record<string,string>}){const c=marineCopy[langOf(t)];if(beach.sand===null)return <div className="detail-card sand-card"><div className="card-icon">🌡️</div><div><p>{t.sand} · {c.official}</p><h2>{c.noData}</h2><span>{c.sandUnavailable}</span></div></div>;const hot=beach.sand>=43;return <div className="detail-card sand-card"><div className="card-icon">🌡️</div><div><p>{t.sand}</p><h2>{beach.sand}<small>°C</small></h2><span>{textOf(t,hot?"sandHot":"sand")}</span></div><RiskPill risk={hot?"danger":"caution"} t={t}/></div>}
function WaveCard({beach,t}:{beach:Beach;t:Record<string,string>}){const c=marineCopy[langOf(t)];if(beach.wave===null)return <div className="detail-card wave-card"><div className="card-icon">🌊</div><div><p>{t.wave} · {c.official}</p><h2>{c.noData}</h2><span>{c.waveUnavailable}</span></div></div>;const r:Risk=beach.wave>=1.3?"danger":beach.wave>=.8?"caution":"safe";return <div className="detail-card wave-card"><div className="card-icon">🌊</div><div><p>{t.wave} · {c.official}</p><h2>{beach.wave}<small>m</small></h2><span>{beach.waveStation?c.waveStation(beach.waveStation):textOf(t,r==="danger"?"waveDanger":"wave")}</span></div><RiskPill risk={r} t={t}/></div>}
function JellyCard({beach,t,goAid}:{beach:Beach;t:Record<string,string>;goAid:()=>void}){const c=marineCopy[langOf(t)],known=beach.jelly!=="unknown";return <div className="detail-card jelly-card"><div className="card-icon">{beach.jellyPresent?<img className="jellyfish-card-image" src="https://cdn.jsdelivr.net/gh/jdecked/twemoji@17.0.2/assets/svg/1fabc.svg" alt=""/>:"✓"}</div><div><p>{t.jelly} · {c.official}</p><h2>{known?(beach.jellyPresent?t[beach.jelly]:c.noJelly):c.noData}</h2><span>{beach.localizedJellyArea??beach.jellyArea}</span></div>{known&&<RiskPill risk={beach.jelly as Risk} t={t}/>}<button className="mini-action" onClick={goAid}>{textOf(t,"jellyAid")}</button></div>}
function ShadeCard({beach,lang,t}:{beach:Beach;lang:Lang;t:Record<string,string>}){const title=(index:number)=>lang==="ko"?beach.shade[index].name:`${t.shade} ${index+1}`;const detail=(index:number)=>lang==="ko"?beach.shade[index].detail:`${t.walk} ${beach.shade[index].walk}${t.min}`;return <div className="detail-card shade-card"><div className="card-icon">🌳</div><div className="shade-copy"><p>{t.shade}</p><h2>{title(0)}</h2><span>{detail(0)} · {t.walk} {beach.shade[0].walk}{t.min}</span></div><div className="shade-next"><b>2</b><span>{title(1)}</span><small>{detail(1)} · {t.walk} {beach.shade[1].walk}{t.min}</small></div></div>}
function TimerCard({t,secondLabel,seconds,running,location,begin,toggle,reset}:{t:Record<string,string>;secondLabel:string;seconds:number;running:boolean;location:string;begin:()=>void;toggle:()=>void;reset:()=>void}){const allow=()=>{"Notification" in window&&Notification.requestPermission()};return <div className="timer-card"><div className="timer-circle" style={{"--progress":`${Math.min(seconds/10*360,360)}deg`} as React.CSSProperties}><div><small>{t.exposure}</small><b>{fmt(seconds)}</b><span>{seconds<10?`${t.next} ${10-seconds}${secondLabel}`:textOf(t,"rest")}</span></div></div><div><p>☀ {location||textOf(t,"location")}</p>{seconds===0?<button className="primary" onClick={begin}>{t.startTimer}</button>:<button className="primary" onClick={toggle}>{running?"Ⅱ "+t.pause:"▶ "+t.resume}</button>}<button className="ghost" onClick={reset}>{t.reset}</button><button className="notify" onClick={allow}>♢ {t.notify}</button></div></div>}
function AidCard({lang}:{lang:Lang}){const content=aidCopy[lang];return <div className="aid-card"><div><img className="jellyfish-card-image" src="https://cdn.jsdelivr.net/gh/jdecked/twemoji@17.0.2/assets/svg/1fabc.svg" alt=""/><h2>{content.title}</h2><p>{content.sub}</p></div><ol>{content.steps.map((step,index)=><li key={step[0]}><b>{String(index+1).padStart(2,"0")}</b><span><strong>{step[0]}</strong><small>{step[1]}</small></span></li>)}</ol></div>}
type Place={icon:string;name:string;meta:string;image:string};
const NEARBY_PLACES:Record<string,Place[]>={
  haeundae:[{icon:"⛵",name:"더베이101",meta:"해운대 · 해변에서 약 1km",image:"https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?auto=format&fit=crop&w=900&q=80"},{icon:"🌲",name:"동백섬",meta:"해운대 · 산책과 그늘",image:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80"}],
  gwangalli:[{icon:"🌉",name:"민락수변공원",meta:"광안리 · 도보 약 10분",image:"https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=900&q=80"},{icon:"☕",name:"광안리 카페거리",meta:"광안리 · 실내 휴식",image:"https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=900&q=80"}],
  songjeong:[{icon:"🏯",name:"해동용궁사",meta:"송정 · 차로 약 10분",image:"https://images.unsplash.com/photo-1548115184-bc6544d06a58?auto=format&fit=crop&w=900&q=80"},{icon:"🌊",name:"청사포 다릿돌전망대",meta:"송정 · 해안 전망",image:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80"}],
  songdo:[{icon:"🚡",name:"송도해상케이블카",meta:"송도 · 해변 바로 옆",image:"https://images.unsplash.com/photo-1551524164-687a55dd1126?auto=format&fit=crop&w=900&q=80"},{icon:"🌿",name:"암남공원",meta:"송도 · 숲길 산책",image:"https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=900&q=80"}],
  dadaepo:[{icon:"⛲",name:"꿈의 낙조분수",meta:"다대포 · 해변 옆",image:"https://images.unsplash.com/photo-1520637836862-4d197d17c90a?auto=format&fit=crop&w=900&q=80"},{icon:"🌅",name:"다대포 해변공원",meta:"다대포 · 그늘 산책",image:"https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=900&q=80"}],
  ilgwang:[{icon:"🍜",name:"기장시장",meta:"일광 · 차로 약 15분",image:"https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=80"},{icon:"🏖️",name:"일광 해안산책로",meta:"일광 · 해변 인근",image:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80"}],
  imrang:[{icon:"⛪",name:"죽성드림성당",meta:"임랑 · 차로 약 10분",image:"https://images.unsplash.com/photo-1520637836862-4d197d17c90a?auto=format&fit=crop&w=900&q=80"},{icon:"🍜",name:"기장시장",meta:"임랑 · 차로 약 15분",image:"https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=80"}],
};

// A local, royalty-free style travel photo keeps recommendation photos reliable offline.
Object.values(NEARBY_PLACES).flat().forEach(place=>{place.image=`${import.meta.env.BASE_URL}free-places/coastal-promenade.png`});

const PLACE_TRANSLATIONS:Record<string,Record<Exclude<Lang,"ko">,{name:string;meta:string}>>={
  "더베이101":{en:{name:"The Bay 101",meta:"Haeundae · about 1 km"},zh:{name:"The Bay 101",meta:"海云台 · 约1公里"},ja:{name:"The Bay 101",meta:"海雲台 · 約1km"},fr:{name:"The Bay 101",meta:"Haeundae · env. 1 km"}},
  "동백섬":{en:{name:"Dongbaekseom Island",meta:"Haeundae · shaded walk"},zh:{name:"冬柏岛",meta:"海云台 · 林荫步道"},ja:{name:"冬柏島",meta:"海雲台 · 木陰の散策路"},fr:{name:"Île Dongbaekseom",meta:"Haeundae · promenade ombragée"}},
  "민락수변공원":{en:{name:"Millak Waterfront Park",meta:"Gwangalli · 10 min walk"},zh:{name:"民乐水边公园",meta:"广安里 · 步行10分钟"},ja:{name:"民楽水辺公園",meta:"広安里 · 徒歩10分"},fr:{name:"Parc de Millak",meta:"Gwangalli · 10 min à pied"}},
  "광안리 카페거리":{en:{name:"Gwangalli Cafe Street",meta:"Gwangalli · indoor break"},zh:{name:"广安里咖啡街",meta:"广安里 · 室内休息"},ja:{name:"広安里カフェ通り",meta:"広安里 · 屋内休憩"},fr:{name:"Rue des cafés de Gwangalli",meta:"Gwangalli · pause intérieure"}},
  "해동용궁사":{en:{name:"Haedong Yonggungsa",meta:"Songjeong · 10 min by car"},zh:{name:"海东龙宫寺",meta:"松亭 · 车程10分钟"},ja:{name:"海東龍宮寺",meta:"松亭 · 車で10分"},fr:{name:"Temple Haedong Yonggungsa",meta:"Songjeong · 10 min en voiture"}},
  "청사포 다릿돌전망대":{en:{name:"Cheongsapo Observatory",meta:"Songjeong · sea view"},zh:{name:"青沙浦踏石观景台",meta:"松亭 · 海景"},ja:{name:"青沙浦タリットル展望台",meta:"松亭 · 海の眺め"},fr:{name:"Observatoire de Cheongsapo",meta:"Songjeong · vue sur mer"}},
  "송도해상케이블카":{en:{name:"Songdo Marine Cable Car",meta:"Songdo · next to the beach"},zh:{name:"松岛海上缆车",meta:"松岛 · 海滩旁"},ja:{name:"松島海上ケーブルカー",meta:"松島 · ビーチのそば"},fr:{name:"Téléphérique marin de Songdo",meta:"Songdo · près de la plage"}},
  "암남공원":{en:{name:"Amnam Park",meta:"Songdo · forest walk"},zh:{name:"岩南公园",meta:"松岛 · 森林步道"},ja:{name:"岩南公園",meta:"松島 · 森の散策"},fr:{name:"Parc d'Amnam",meta:"Songdo · promenade en forêt"}},
  "꿈의 낙조분수":{en:{name:"Sunset Fountain of Dreams",meta:"Dadaepo · beside the beach"},zh:{name:"梦幻落照喷泉",meta:"多大浦 · 海滩旁"},ja:{name:"夢の落照噴水",meta:"多大浦 · ビーチのそば"},fr:{name:"Fontaine du coucher de soleil",meta:"Dadaepo · près de la plage"}},
  "다대포 해변공원":{en:{name:"Dadaepo Beach Park",meta:"Dadaepo · shaded walk"},zh:{name:"多大浦海滨公园",meta:"多大浦 · 林荫步道"},ja:{name:"多大浦海浜公園",meta:"多大浦 · 木陰の散策"},fr:{name:"Parc de plage de Dadaepo",meta:"Dadaepo · promenade ombragée"}},
  "기장시장":{en:{name:"Gijang Market",meta:"Gijang · 15 min by car"},zh:{name:"机张市场",meta:"机张 · 车程15分钟"},ja:{name:"機張市場",meta:"機張 · 車で15分"},fr:{name:"Marché de Gijang",meta:"Gijang · 15 min en voiture"}},
  "일광 해안산책로":{en:{name:"Ilgwang Coastal Trail",meta:"Ilgwang · near the beach"},zh:{name:"日光海岸步道",meta:"日光 · 海滩附近"},ja:{name:"日光海岸散策路",meta:"日光 · ビーチの近く"},fr:{name:"Sentier côtier d'Ilgwang",meta:"Ilgwang · près de la plage"}},
  "죽성드림성당":{en:{name:"Jukseong Dream Church",meta:"Imrang · 10 min by car"},zh:{name:"竹城梦幻教堂",meta:"林浪 · 车程10分钟"},ja:{name:"竹城ドリーム教会",meta:"林浪 · 車で10分"},fr:{name:"Église de rêve de Jukseong",meta:"Imrang · 10 min en voiture"}},
};
type AiPlace={id:string;name:string;photoTitle?:string;category:string;coordinate:[number,number];distanceKm:number;reason:string;openNow?:boolean;mapsUrl:string};
const AI_COPY:Record<Lang,Record<string,string>>={
  ko:{eyebrow:"GPS · GEMINI AI",heading:"선택한 해수욕장 주변 명소",description:"부산 현재 시각에 일반 영업시간상 문을 연 비해변 장소를 추천해요.",button:"다른 장소 추천",locating:"현재 위치 확인 중…",loading:"현재 영업 중인 주변 장소를 찾는 중…",permission:"위치 권한을 허용해 주세요.",failed:"추천을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.",closed:"현재 시간에 영업 중인 가까운 장소가 없어요.",mapped:"현재 영업 중인 가까운 장소를 지도에 표시했어요.",safe:"영업 중 · 바닷가 제외"},
  en:{eyebrow:"GPS · GEMINI AI",heading:"Places near the selected beach",description:"Recommends non-beach places open during regular hours at the current Busan time.",button:"Show different places",locating:"Checking your location…",loading:"Finding nearby places open now…",permission:"Please allow location access.",failed:"Recommendations could not be loaded. Try again shortly.",closed:"No nearby places are open at this time.",mapped:"Nearby places open now are shown on the map.",safe:"Open now · no beaches"},
  zh:{eyebrow:"GPS · GEMINI AI",heading:"所选海滩附近的景点",description:"根据釜山当前时间推荐正常营业中的非海滨地点。",button:"推荐其他地点",locating:"正在确认当前位置…",loading:"正在寻找当前营业的附近地点…",permission:"请允许访问位置信息。",failed:"无法加载推荐，请稍后再试。",closed:"当前时间附近没有营业中的地点。",mapped:"当前营业的附近地点已显示在地图上。",safe:"营业中 · 不含海滩"},
  ja:{eyebrow:"GPS · GEMINI AI",heading:"選択したビーチ周辺のスポット",description:"釜山の現在時刻に通常営業時間内で開いている海辺以外の場所をおすすめします。",button:"別の場所をおすすめ",locating:"現在地を確認中…",loading:"現在営業中の周辺スポットを検索中…",permission:"位置情報を許可してください。",failed:"おすすめを読み込めませんでした。少し待って再試行してください。",closed:"現在営業中の近い場所がありません。",mapped:"現在営業中の近い場所を地図に表示しました。",safe:"営業中 · 海辺以外"},
  fr:{eyebrow:"GPS · GEMINI AI",heading:"Lieux près de la plage sélectionnée",description:"Recommande des lieux hors plage ouverts aux horaires habituels à l’heure actuelle de Busan.",button:"Voir d’autres lieux",locating:"Localisation en cours…",loading:"Recherche de lieux ouverts à proximité…",permission:"Veuillez autoriser la localisation.",failed:"Impossible de charger les recommandations. Réessayez bientôt.",closed:"Aucun lieu proche n’est ouvert actuellement.",mapped:"Les lieux proches actuellement ouverts sont sur la carte.",safe:"Ouvert · sans plage"},
};
function PlanCard({beach,lang,currentResults,onLocated,onResults}:{beach:Beach;lang:Lang;t:Record<string,string>;currentResults:AiPlace[];onLocated:(position:[number,number])=>void;onResults:(places:AiPlace[])=>void}){
  const c=AI_COPY[lang],[status,setStatus]=useState<"idle"|"locating"|"loading">("idle"),[mapped,setMapped]=useState(false),[error,setError]=useState("");
  const autoRequestedFor=useRef("");
  const recommend=()=>{
    const excludeIds=mapped?currentResults.map(place=>place.id):[];
    setError("");setMapped(false);onResults([]);setStatus("locating");
    if(!navigator.geolocation){setError(c.permission);setStatus("idle");return}
    navigator.geolocation.getCurrentPosition(async position=>{
      onLocated([position.coords.latitude,position.coords.longitude]);
      setStatus("loading");
      try{
        const endpoint=window.location.hostname.endsWith("github.io")?"https://tteubadaba-busan.vercel.app/api/recommend":"/api/recommend";
        const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({latitude:position.coords.latitude,longitude:position.coords.longitude,lang,beach:beach.ko,excludeIds})});
        const data=await response.json();
        if(!response.ok||!Array.isArray(data.recommendations)){setError(data.code==="NO_OPEN_PLACES"?c.closed:c.failed);return}
        onResults(data.recommendations);setMapped(true);
      }catch{setError(c.failed)}finally{setStatus("idle")}
    },()=>{setError(c.permission);setStatus("idle")},{enableHighAccuracy:false,timeout:10000,maximumAge:300000});
  };
  useEffect(()=>{
    if(autoRequestedFor.current===beach.id)return;
    autoRequestedFor.current=beach.id;
    onResults([]);setError("");
    recommend();
  },[beach.id]);
  const busy=status!=="idle";
  return <div className="ai-plan-card"><div><p>{c.eyebrow}</p><h2>{c.heading}</h2><small>{mapped?c.mapped:c.description}</small></div><span className="ai-no-beach">🏙️ {c.safe}</span><button className="primary ai-recommend-button" onClick={recommend} disabled={busy}>📍 {status==="locating"?c.locating:status==="loading"?c.loading:c.button}</button>{error&&<em className="ai-error">{error}</em>}</div>;
}
function PlacePhotoModal({place,copy,onClose}:{place:Place;copy:{name:string;meta:string};onClose:()=>void}){useEffect(()=>{const close=(event:KeyboardEvent)=>event.key==="Escape"&&onClose();window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[onClose]);return createPortal(<div role="dialog" aria-modal="true" aria-label={copy.name} onClick={onClose} style={{position:"fixed",zIndex:2147483647,inset:0,display:"grid",placeItems:"center",padding:"clamp(16px,4vw,48px)",background:"rgba(5,20,30,.82)",backdropFilter:"blur(7px)"}}><section onClick={e=>e.stopPropagation()} style={{position:"relative",zIndex:1,width:"min(980px,100%)",maxHeight:"92vh",overflow:"hidden",borderRadius:"24px",background:"#fff",boxShadow:"0 28px 100px #000b"}}><img src={place.image} alt={`${copy.name} 사진`} style={{display:"block",width:"100%",height:"min(68vh,650px)",objectFit:"cover"}}/><div style={{padding:"20px 26px 24px"}}><p style={{margin:0,color:"#f36e50",fontSize:"11px",fontWeight:900,letterSpacing:"1px"}}>NEARBY RECOMMENDATION</p><h2 style={{margin:"5px 0",color:"#123d56",fontSize:"clamp(24px,4vw,34px)"}}>{copy.name}</h2><p style={{margin:0,color:"#6f8188",fontSize:"14px"}}>{copy.meta}</p></div><button onClick={onClose} aria-label="닫기" style={{position:"absolute",top:"14px",right:"14px",display:"grid",placeItems:"center",width:"42px",height:"42px",border:0,borderRadius:"50%",background:"#123d56e8",color:"white",fontSize:"25px",cursor:"pointer"}}>×</button></section></div>,document.body)}
